language: node_js
node_js:
  - "6"
sudo: false
script: "node node_modules/mocha/bin/mocha test/setup/node.js test/unit"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
